apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    app: "{{ .Chart.Name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  name: "{{ .Chart.Name }}"
spec:
  backend:
    serviceName: "{{ .Chart.Name }}"
    servicePort: 80
