apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: "{{ .Chart.Name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  name: "{{ .Chart.Name }}"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: "{{ .Chart.Name }}"
    spec:
      containers:
        - name: "{{ .Chart.Name }}"
          image: "{{ .Values.image }}:{{ .Values.dockerTag }}"
          imagePullPolicy: "Always"
          ports:
            - containerPort: 3000
